name: validify
description: "A powerful validation package designed to simplify and simplify form validation for Dart and Flutter."
version: 0.0.2
homepage: https://github.com/bedirhanssaglam/validify
repository: https://github.com/bedirhanssaglam/validify
issue_tracker: https://github.com/bedirhanssaglam/validify/issues
topics: [form, validation]

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
